// Primary KPI row — MCRR / LCS / Monthly Impact.
// Vertical-aware label via getVerticalMeta.
// (1행 핵심 KPI — MCRR / LCS / Total Impact, vertical-aware label)
import { useEffect, useState } from 'react'
import api from '../../../../core/api'
import { getVerticalMeta } from '../../../../core/verticalLabels'
import styles from '../Overview.module.css'

type Period = 'today' | 'week' | 'month' | 'all'

interface Metrics {
  mcrr: number
  lcs: number
  lcr: number
  upselling_value: number
  monthly_impact: number
  total_calls: number
  successful_calls: number
  total_ai_revenue: number
  avg_ticket: number
  success_rate: number
  using_real_busy_data: boolean
}

const fmt = (n: number) =>
  `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export default function PrimaryKpiSection({
  period,
  industry,
  onMetrics,
}: {
  period: Period
  industry: string | null
  onMetrics?: (m: Metrics | null) => void
}) {
  const meta = getVerticalMeta(industry ?? 'restaurant')
  const [m, setM] = useState<Metrics | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    api
      .get(`/store/metrics?period=${period}`)
      .then((r) => {
        setM(r.data)
        onMetrics?.(r.data)
      })
      .finally(() => setLoading(false))
  }, [period, onMetrics])

  return (
    <div className={styles.kpiRow}>
      <div className={`${styles.kpiCard} ${styles.kpiGreen}`}>
        <div className={styles.kpiTop}>
          <span className={styles.kpiLabel}>{meta.primaryRevenueLabel}</span>
          <span className={styles.kpiBadge}>MCRR</span>
        </div>
        <div className={styles.kpiValue}>{loading ? '—' : fmt(m?.mcrr ?? 0)}</div>
        <div className={styles.kpiSub}>
          {m?.using_real_busy_data
            ? 'Busy-hour calls answered by AI × success rate × avg ticket'
            : 'Est. missed calls × AI success rate × avg ticket'}
        </div>
      </div>

      <div className={`${styles.kpiCard} ${styles.kpiBlue}`}>
        <div className={styles.kpiTop}>
          <span className={styles.kpiLabel}>Labor Cost Savings</span>
          <span className={styles.kpiBadge}>LCS</span>
        </div>
        <div className={styles.kpiValue}>{loading ? '—' : fmt(m?.lcs ?? 0)}</div>
        <div className={styles.kpiSub}>
          AI call hours × $20/hr — staff freed for floor service
        </div>
      </div>

      <div className={`${styles.kpiCard} ${styles.kpiImpact}`}>
        <div className={styles.kpiTop}>
          <span className={styles.kpiLabel}>Total Monthly Impact</span>
          <span className={styles.kpiBadge}>PHRC + LCS + UV</span>
        </div>
        <div className={`${styles.kpiValue} ${styles.kpiValueLarge}`}>
          {loading ? '—' : fmt(m?.monthly_impact ?? 0)}
        </div>
        <div className={styles.kpiSub}>
          {m && m.total_ai_revenue > 0
            ? `${((m.monthly_impact / m.total_ai_revenue) * 100).toFixed(1)}% of AI-processed revenue`
            : 'Total economic value generated by AI'}
        </div>
      </div>
    </div>
  )
}

export type { Metrics, Period }
